# Generated by Django 5.2 on 2025-08-14 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_serviceproviderprofile_profile_embedding"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceproviderprofile",
            name="growbal_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
