# Generated by Django 5.2 on 2025-06-16 08:24

import django.db.models.deletion
import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_title",
                    models.CharField(
                        blank=True, default=None, max_length=255, null=True
                    ),
                ),
                (
                    "service_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "general_service_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    "rating_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "rating_description",
                    models.TextField(blank=True, default=None, null=True),
                ),
                ("pricing", models.TextField(blank=True, default=None, null=True)),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="accounts.serviceproviderprofile",
                    ),
                ),
                (
                    "service_tags",
                    taggit.managers.TaggableManager(
                        blank=True,
                        help_text="A comma-separated list of tags.",
                        through="taggit.TaggedItem",
                        to="taggit.Tag",
                        verbose_name="Tags",
                    ),
                ),
            ],
        ),
    ]
