# Generated by Django 5.2 on 2025-07-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="auth_user_id",
            field=models.IntegerField(
                blank=True,
                help_text="External MySQL user ID for authenticated users",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="authentication_method",
            field=models.CharField(
                choices=[
                    ("form", "Form Login"),
                    ("sso", "Single Sign-On"),
                    ("anonymous", "Anonymous"),
                ],
                default="anonymous",
                help_text="Method used for authentication",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="chatsession",
            name="is_authenticated",
            field=models.BooleanField(
                default=False, help_text="Whether this session is authenticated"
            ),
        ),
    ]
