# Generated by Django 5.2 on 2025-08-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0002_chatsession_auth_user_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Optional title for the chat session",
                max_length=200,
            ),
        ),
    ]
